TARGET1 = Game
TARGET2 = Checkers
TARGET3 = Menu
TARGET4 = Piece
TARGET5 = Tile
TARGET6 = Pause
TARGET7 = Symbol
TARGET8 = Win
TARGET9 = Depend
TARGET10 = images
TARGET11 = music

COMP = javac
RUN = java

$(TARGET1) : $(TARGET1).java $(TARGET2).java $(TARGET3).java $(TARGET4).java $(TARGET5).java $(TARGET6).java $(TARGET7).java $(TARGET8).java $(TARGET9).java $(TARGET10) $(TARGET11)

				$(COMP) $(TARGET1).java $(TARGET2).java $(TARGET3).java $(TARGET4).java $(TARGET5).java $(TARGET6).java $(TARGET7).java $(TARGET8).java $(TARGET9).java

clean :
				rm -f *.class
				
run :
				$(RUN) $(TARGET1)